stack-nix.yaml
stack.yaml

Without `enable: true` hard coded in the stack.yaml, users can decide
whether `--nix` should be on or not.

Merge stack-nix.yaml and stack.yaml.

---

inline-js/package.yaml
inline-js/src/Language/JavaScript/Inline.hs
inline-js/tests/Tests/Quotation.hs

Additional work to make templating parameters into the `js` quasiquoter work.

Add template params to quasiquoter

---

inline-js-core/src/Language/JavaScript/Inline/Session.hs
inline-js-core/src/Language/JavaScript/Inline/Transport/Process.hs
inline-js-core/src/Language/JavaScript/Inline/Transport/Utils.hs
inline-js/tests/Tests/Echo.hs

Changes:
* In the "process" transport, solved a bug in `recvData` which may return incomplete messages. Now it's fully strict and either returns the whole message or throws.
* `sendData` now pushes the message to a send queue and returns immediately, instead of holding a mutex.
* `recvData` is no longer susceptible to a race condition when a thread is blocked on `recvData`, but the expected message is received in another thread.

Include utils to make transports thread-safe

---

inline-js-core/src/Language/JavaScript/Inline/Command.hs
inline-js-core/src/Language/JavaScript/Inline/Message/Class.hs
inline-js-core/src/Language/JavaScript/Inline/Message/Eval.hs
inline-js-core/src/Language/JavaScript/Inline/Session.hs
inline-js/tests/Tests/Evaluation.hs
inline-js/tests/Tests/Helpers/Message.hs

We used to only support a single kind of messages: eval requests/responses. This PR adds a `Message` class, and make the `send`/`recv` functions in `Language.JavaScript.Inline.Session` operate on generic messages. This makes it easy to extend the node eval server with new message handlers.

Generic Message class

---

.circleci/config.yml
inline-js-core/jsbits/eval.mjs
inline-js-core/src/Language/JavaScript/Inline/Command.hs
inline-js-core/src/Language/JavaScript/Inline/JSCode.hs
inline-js-core/src/Language/JavaScript/Inline/Message/Class.hs
inline-js-core/src/Language/JavaScript/Inline/Message/Eval.hs
inline-js-core/src/Language/JavaScript/Inline/Session.hs
inline-js/src/Language/JavaScript/Inline.hs
inline-js/tests/Tests/Evaluation.hs
inline-js/tests/Tests/Helpers/Message.hs
inline-js/tests/Tests/PingPong.hs
stack.yaml

Notable changes:
* We used to assume all returned data is JSON-encoded and implicitly invoke `JSON.stringify()` in the eval server. Now the assumption no longer holds: `EvalResponse` is parameterised by either `ByteString` or `JSVal`, and for `EvalResponse ByteString`, the returned data is only wrapped in `Buffer.from()`, so it can be any kind of binary data. Manually call `JSON.stringify()` if JSON-encoded return data is needed.
* `newJSVal` is now implicitly called in the eval server. If we need to return a `JSVal` from node, simply make sure the response type is `EvalResponse JSVal`.
* Implemented `AllocRequest` to send a raw Haskell buffer to node.
* `JSRef`s renamed to `JSVal`s so more consistent with asterius.
The higher-level TH quotes in `inline-js` should still continue to work …

Direct support of binary data marshaling

---

inline-js-core/jsbits/echo.mjs
inline-js-core/jsbits/eval.mjs
inline-js-core/src/Language/JavaScript/Inline/Session.hs
inline-js-core/src/Language/JavaScript/Inline/Transport/Process.hs
inline-js/tests/Tests/Echo.hs

When using `inline-js-core` to evaluate wasm/js produced by asterius codegen, the pipes are broken due to calling of `console` API in evaluated code. It's possible to override `console` by providing a fake `console` interface in the contexified object in the eval server, but apparently a simpler fix is creating file descriptors in Haskell, then passing those to the eval server, and stdin/stdout/stderr of node remain untouched.

Use fds instead of stdin/stdout for Transport

---

inline-js-core/jsbits/eval.mjs
inline-js-core/src/Language/JavaScript/Inline/Command.hs
inline-js-core/src/Language/JavaScript/Inline/Message/Eval.hs
inline-js/testdata/echo.mjs
inline-js/testdata/identity.mjs
inline-js/tests/Main.hs
inline-js/tests/Tests/Echo.hs
inline-js/tests/Tests/PingPong.hs

In nodejs it's a bit tricky to `import()` a script when it's in a different directory than `eval.mjs`; changing working directory only works for old-style `require()`. Now we implement that as a built-in request; given an absolute `FilePath` to an entry `.mjs`, this `import()`s the entry script along with its deps, and return as a `JSVal`.

Implement "importMJS" command

---

inline-js-core/inline-js-core.cabal
inline-js-core/jsbits/eval.mjs
inline-js-core/jsbits/jsval.mjs
inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Command.hs
inline-js-core/src/Language/JavaScript/Inline/Core/HSCode.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Internal.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message/Class.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message/HSCode.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs
inline-js/inline-js.cabal
inline-js/tests/Tests/Evaluation.hs
inline-js/tests/Tests/PingPong.hs

It's possible. And needed for `ahc-iserv` to send back ghc-related queries from the node runner.
Marshaling *different* types of Haskell functions is hard though (even if you're not going as far as `singletons`-related typesafe craziness), my hardship challenge quota already ran out for this month. So right now we only support one type of Haskell function:
```
newtype HsFunc = HSFunc ([ByteString] -> IO ByteString)
```
It can be exported to JavaScript, and the wrapper function returned as `JSVal`. When the wrapper function is called, the binary argument list is sent to Haskell, the result computed and returned in a forked Haskell thread, and finally, the wrapper function's returned `Promise` either resolves or rejects.
If people need more interesting types in arguments/return value, for …

Export a Haskell function as a JavaScript function

---

README.md
inline-js-core/jsbits/eval.mjs
inline-js-core/jsbits/transport.mjs
inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Command.hs
inline-js-core/src/Language/JavaScript/Inline/Core/HSCode.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message/HSCode.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs
inline-js/tests/Tests/PingPong.hs

As a sequel of #20.
Consider this use case: export a Haskell function, then use it as a WebAssembly import. This won't work yet since the wrapper function returns a `Promise` and is async by nature, and both the WebAssembly spec and V8 doesn't allow using async functions as imports, since that requires "suspending"/"resuming" of WebAssembly runtime state. So we need to implement a "sync mode" for this exact corner case.
Basic ideas:
* It's possibly simpler to rely on something like `fibers`, but they rely on building C++ which introduces extra pain, so we'll base on something simpler here: worker threads.
* Main logic of the "eval server" (e.g. eval/resolution, JSVal) stays in the main thread. The "transport" logic is moved to a worker thread.
* The two threads synchronize on a "shared …

Implement "sync mode" of exporting Haskell functions to JavaScript

---

inline-js-core/jsbits/eval.mjs
inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Command.hs

This PR adds stack traces to the returned error message when it's available. There's also an `EvalException` exception type added, which can be caught when using high-level commands like `eval` to obtain the raw error message.

Add stack traces to eval server's returned error message

---

.circleci/config.yml
README.md
inline-js-core/inline-js-core.cabal
inline-js-core/src/Language/JavaScript/Inline/Core/NodeVersion.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs
stack.yaml

This PR ensures the node version is at least 11; otherwise `JSSession` initialization will fail. The node version requirement is now written on readme.
Also, we test against node 11/12/13 on CI. Node 13 is provided by V8 team's node integration build.

Enforce correct node version

---

.circleci/config.yml
README.md
inline-js-core/jsbits/context.mjs
inline-js-core/jsbits/eval.mjs
inline-js-core/src/Language/JavaScript/Inline/Core/NodeVersion.hs
inline-js/inline-js.cabal
inline-js/tests/Tests/Evaluation.hs
inline-js/tests/Tests/LeftPad.hs
inline-js/tests/Tests/Quotation.hs
stack.yaml

* Add preliminary support for `require()`
* Bump minimal required node version to `12.2`
* Set up the unresolved promise rejection handler in `eval.mjs`
* Switch from `tasty-hspec` to `tasty-hunit` for all tests
* Bump stackage resolver & nixpkgs revision
* Fix CI due to losing access to resource classes

Misc improvements

---

.circleci/config.yml
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs

This PR adds an extra `nodeExtraEnv` field to `JSSessionOpts`, so extra environment variables can be passed to `node`.

Support extra environment variables to be passed to node

---

.circleci/config.yml
inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Command.hs
inline-js-core/src/Language/JavaScript/Inline/Core/HSCode.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Internal.hs
inline-js-core/src/Language/JavaScript/Inline/Core/JSCode.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message/Class.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message/Eval.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message/HSCode.hs
inline-js-core/src/Language/JavaScript/Inline/Core/MessageCounter.hs
inline-js-core/src/Language/JavaScript/Inline/Core/NodeVersion.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs
inline-js/src/Language/JavaScript/Inline.hs
inline-js/src/Language/JavaScript/Inline/Class.hs
inline-js/tests/Main.hs
inline-js/tests/Tests/Echo.hs
inline-js/tests/Tests/Evaluation.hs
inline-js/tests/Tests/LeftPad.hs
inline-js/tests/Tests/PingPong.hs
inline-js/tests/Tests/Quotation.hs
inline-js/tests/Tests/Wasm.hs
stack.yaml

Following changes in `asterius`, we apply `ormolu` to existing Haskell code before further refactoring, and designate `ormolu` as our official formatter here.

Apply `ormolu` to existing Haskell codebase

---

inline-js-core/jsbits/eval.mjs
inline-js-core/jsbits/pipe.mjs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs

Previously, we implement `closeJSSession` by forcibly terminating the send/recv threads and the `node` process. This approach works only when no send/recv action is ongoing, and seems to be the source of occasional broken pipe bugs. We now implement a more graceful `closeJSSession`:
* A special `SHUTDOWN` message is enqueued to be picked up and sent by the send thread.
* When the eval server receives `SHUTDOWN`, it no longer processes the next incoming message. When all messages are handled, the event queue will be empty, and `node` will shutdown gracefully.
* The infinite loop in the send/recv threads are wrapped with `tryAny`, so when `node` shuts down and the pipes are closed, the threads will silently exit instead of invoking an unhandled exception handler.
This shall also clarify the …

Implement more graceful `closeJSSession`

---

inline-js-core/inline-js-core.cabal
inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Command.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Exception.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message/Class.hs
inline-js-core/src/Language/JavaScript/Inline/Core/NodeVersion.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs

This PR introduces `InlineJSException` as the uniform type of exceptions to be handled by library users. Some previously ad hoc `fail` calls are replaced with the corresponding variant of `InlineJSException`.

A uniform exception type

---

.circleci/config.yml
stack.yaml

This PR uses https://github.com/TerrorJack/node-fetcher to set up `node`. Now we test against `v12`, `v13` and `v8-canary` for both linux and darwin. The previously broken `v8` job is now fixed.

Proper CI config

---

.circleci/config.yml
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs
inline-js/tests/Tests/Echo.hs
inline-js/tests/Tests/PingPong.hs
stack.yaml

Closes unneeded handles in the host process; seems to mitigate the broken pipe problem. Increases some constants in the test suite to enhance fuzzing. Also bumps the stackage resolver.

Misc fixes

---

.circleci/config.yml
inline-js-core/inline-js-core.cabal
inline-js-core/jsbits/eval.js
inline-js-core/jsbits/jsval.js
inline-js-core/jsbits/lock.js
inline-js-core/jsbits/pipe.js
inline-js-core/src/Language/JavaScript/Inline/Core/JSCode.hs
inline-js-core/src/Language/JavaScript/Inline/Core/NodeVersion.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs

This PR uses CommonJS for `jsbits` in `inline-js-core`. This allows us to assign a global `require` directly using the `require` in the scope of `eval.js`, instead of using `module.createRequire`. The `node` version requirement is relaxed to `v10.15.3`.

Use CommonJS for jsbits in inline-js-core

---

.circleci/config.yml
stack.yaml

This PR adds jobs for building & testing with cabal for linux & darwin, using `ghcup` to set up the toolchain.

Test cabal support on CI

---

inline-js-core/jsbits/eval.js
inline-js-core/jsbits/jsval.js
inline-js-core/jsbits/lock.js
inline-js-core/jsbits/pipe.js
inline-js/src/Language/JavaScript/Inline/Class.hs

This PR uses `ArrayBuffer` as the JavaScript buffer type for `alloc` commands and the `ToJSCode` instances of `ByteString` types. There's some extra copying overhead for now, but the transition from `Buffer` to `ArrayBuffer` should be done sooner or later anyway, since `ArrayBuffer` works across node & browsers.

Use `ArrayBuffer` when marshaling Haskell ByteStrings

---

inline-js-core/jsbits/eval.js

Fixes the handling of `SHUTDOWN` message introduced in #39.

Do not pass shutdown message to handleHostMessage

---

.circleci/config.yml
inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Exception.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs

Previously, when the session is closed, the send/recv threads die, but the send/recv queues are still functional, so when a command is invoked, the message stays in the send queue, and the returned continuation will block indefinitely. We now implement a `SessionClosed` exception variant, so after a session is closed, further attempts to send messages will immediately throw.

Implement `SessionClosed` exception

---

.circleci/config.yml
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs
stack.yaml

When hacking on the host/node wire protocol and changing the eval server js code, we used to break stuff and need to regularly set `nodeStdErrInherit = True` in the test suite to see the `stderr` of the `node` process; now we'll just flip it on by default if `INLINE_JS_DEBUG` environment variable is present. Also, a resolver bump sneaks in.

Add a "debug mode"

---

inline-js-core/jsbits/index.js
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs

The root directory can be inferred from `__dirname` directly.

Remove unneeded INLINE_JS_ROOT environment variable

---

.github/workflows/pipeline.yml
README.md
inline-js-core/inline-js-core.cabal
inline-js-core/package.yaml

Minor fixes in the package metadata to conform to the hackage standard, and produce sdist tarballs on CI; also runs `cabal check` to prevent regression here.

Fix sdist tarballs

---

inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/IPC.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Instruction.hs
inline-js-core/src/Language/JavaScript/Inline/Core/JSVal.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message.hs
inline-js/src/Language/JavaScript/Inline.hs
inline-js/src/Language/JavaScript/Inline/Class.hs
inline-js/src/Language/JavaScript/Inline/TH.hs
inline-js/tests/inline-js-tests.hs
stack.yaml

Massive renamings in public API. The docs are adjusted accordingly.
* `JSCode` is renamed to `JSExpr` for more clarity: it must be a valid JavaScript expression
* `ToJSCode`/`FromEvalResult` are renamed to `ToJS/FromJS`, not because we want to save a few keystrokes, but because they'll also be responsible for data marshaling when exporting Haskell functions to JavaScript, so we should use generalized names starting from now.
* We now use `evalJSON` in `inline-js-core` for the `FromJS` instance of `Aeson a`. The relevant `EncodedJSON` wrapper type is also exported, in case people would like to work with a non-`aeson` JSON library.

API & docs adjustments

---

inline-js-core/jsbits/index.js
inline-js-core/src/Language/JavaScript/Inline/Core/Message.hs

The logic to decode a `JSExpr` from a message buffer and evaluate it has been factored out to the `decodeAndEvalJSExpr` method. Later we'll add other variants of messages which include `JSExpr` payload (e.g. `HSEvalResponse`), thus the refactoring. `decodeAndEvalJSExpr` support specifying whether the `JSExpr` should be evaluated in async/sync mode.

Factor out `decodeAndEvalJSExpr`

---

inline-js-core/jsbits/index.js

When the session is closed, no `JSValFree` messages may be received by `node` again. We should drop all `JSVal`s to plug a space leak here, just in case `node` needs to run for some more time.

Clear all JSVal on close

---

inline-js-core/inline-js-core.cabal
inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Class.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message.hs
inline-js/inline-js.cabal
inline-js/src/Language/JavaScript/Inline.hs
inline-js/src/Language/JavaScript/Inline/Aeson.hs
inline-js/src/Language/JavaScript/Inline/Class.hs
inline-js/src/Language/JavaScript/Inline/TH.hs
inline-js/tests/inline-js-tests.hs

One step further on implementing Haskell function exports.
* The `ToJS`/`FromJS` type classes are now moved to `inline-js-core`. `inline-js` adds `aeson` marshaling support on top of that.
* `inline-js-core` only exports the polymorphic `eval` function.
* Besides `EncodedJSON`, there's a new `EncodedString` newtype wrapper for marshaling strings, since it's a really common use case.

Move ToJS/FromJS type classes to inline-js-core

---

.github/workflows/pipeline.yml
stack.yaml

Use a single `upload-artifact` step for uploading sdist/haddock tarballs.

Simplify sdist/haddock job scripts

---

inline-js-core/src/Language/JavaScript/Inline/Core/Class.hs

Otherwise we'd get something like `{"type": "Buffer", "data": [...]}` at runtime instead, as a result of calling `JSON.stringify()` on a `Buffer` directly.

Fix EncodedJSON ToJS instance

---

README.md
inline-js-core/inline-js-core.cabal
inline-js-core/jsbits/index.js
inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Export.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Instruction.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs
inline-js/tests/inline-js-tests.hs

Left to future PRs:
* Support sync mode of exporting, so that you can use `inline-js` as a wasm runtime.
* Proper resource management of exported functions. Currently, they're never freed. And we can't use weak pointers in `node`. So for exported functions, we may want to introduce explicit `freeJSVal`.

Implement Haskell function exporting

---

README.md
inline-js-core/jsbits/index.js
inline-js-core/src/Language/JavaScript/Inline/Core.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Export.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Instruction.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Message.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs
inline-js/tests/inline-js-tests.hs

Haskell functions can now be exported as JavaScript sync functions. The main desired use case is using `inline-js` as the infrastructure of running WebAssembly modules, since host Haskell functions can now be used as wasm imports.

Implement sync mode of Haskell function exporting

---

inline-js-core/inline-js-core.cabal
inline-js-core/package.yaml
inline-js-core/src/Language/JavaScript/Inline/Core/Instruction.hs
inline-js-core/src/Language/JavaScript/Inline/Core/Session.hs

When a `FatalError` message is received, all pending eval requests must be fulfilled with an exception. Previously, we had to keep a set of all pending requests so the `FatalError` message handler can traverse them. This seems to be an unnecessary complication.
This PR uses an STM-based approach instead: each eval request polls from two inboxes, one is the result inbox, the other is the fatal error inbox. The `FatalError` message handler only needs to fill the fatal error inbox, and all pending requests will automatically resolve with that error.
One minor problem compared to `MVar`-based inboxes: the thunks returned by the eval functions may not be safe to use inside other STM logic, due to the nested `atomically` restriction of STM. IMHO the benefit of simplified implementation …

Simplify handling of FatalError messages

---

.github/workflows/pipeline.yml
README.md
cabal.project
inline-js-examples/src/Language/JavaScript/Inline/Examples/Stream.hs
inline-js-examples/src/Language/JavaScript/Inline/Examples/Wasm.hs
inline-js-tests/app/inline-js-tests.hs
inline-js/inline-js.cabal
inline-js/package.yaml
inline-js/src/Language/JavaScript/Inline.hs
inline-js/src/Language/JavaScript/Inline/JSParse.hs
inline-js/src/Language/JavaScript/Inline/TH.hs
nix/sources.json

This PR unifies `expr`/`block` TH quasi-quoters to a single `js` quasi-quoter. `js` will attempt to parse the inline JS code as a single expression, and then fall back to parsing as a whole script if that fails. This leads to a cleaner and more uniform API.

Unify expr/block TH quasi-quoters
